# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RC.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(920, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 22))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setAccessibleName("")
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_1 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy)
        self.groupBox_1.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_1.setAutoFillBackground(False)
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setCheckable(False)
        self.groupBox_1.setChecked(False)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rect = QtWidgets.QRadioButton(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rect.sizePolicy().hasHeightForWidth())
        self.rect.setSizePolicy(sizePolicy)
        self.rect.setChecked(True)
        self.rect.setObjectName("rect")
        self.verticalLayout.addWidget(self.rect)
        self.circ = QtWidgets.QRadioButton(self.groupBox_1)
        self.circ.setObjectName("circ")
        self.verticalLayout.addWidget(self.circ)
        self.tavr = QtWidgets.QRadioButton(self.groupBox_1)
        self.tavr.setObjectName("tavr")
        self.verticalLayout.addWidget(self.tavr)
        self.shell = QtWidgets.QRadioButton(self.groupBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shell.sizePolicy().hasHeightForWidth())
        self.shell.setSizePolicy(sizePolicy)
        self.shell.setCheckable(True)
        self.shell.setChecked(False)
        self.shell.setAutoRepeat(False)
        self.shell.setObjectName("shell")
        self.verticalLayout.addWidget(self.shell)
        self.horizontalLayout_5.addWidget(self.groupBox_1, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bpolk = QtWidgets.QLineEdit(self.tab_1)
        self.bpolk.setObjectName("bpolk")
        self.gridLayout.addWidget(self.bpolk, 4, 1, 1, 1)
        self.hpolk = QtWidgets.QLineEdit(self.tab_1)
        self.hpolk.setObjectName("hpolk")
        self.gridLayout.addWidget(self.hpolk, 3, 1, 1, 1)
        self.brebr = QtWidgets.QLineEdit(self.tab_1)
        self.brebr.setObjectName("brebr")
        self.gridLayout.addWidget(self.brebr, 6, 1, 1, 1)
        self.hrebr = QtWidgets.QLineEdit(self.tab_1)
        self.hrebr.setObjectName("hrebr")
        self.gridLayout.addWidget(self.hrebr, 5, 1, 1, 1)
        self.nbRcir_lb = QtWidgets.QLabel(self.tab_1)
        self.nbRcir_lb.setObjectName("nbRcir_lb")
        self.gridLayout.addWidget(self.nbRcir_lb, 7, 0, 1, 1)
        self.nbRcir = QtWidgets.QLineEdit(self.tab_1)
        self.nbRcir.setObjectName("nbRcir")
        self.gridLayout.addWidget(self.nbRcir, 7, 1, 1, 1)
        self.nbrcir = QtWidgets.QLineEdit(self.tab_1)
        self.nbrcir.setObjectName("nbrcir")
        self.gridLayout.addWidget(self.nbrcir, 8, 1, 1, 1)
        self.nsjcir_lb = QtWidgets.QLabel(self.tab_1)
        self.nsjcir_lb.setObjectName("nsjcir_lb")
        self.gridLayout.addWidget(self.nsjcir_lb, 11, 0, 1, 1)
        self.Rcir = QtWidgets.QLineEdit(self.tab_1)
        self.Rcir.setObjectName("Rcir")
        self.gridLayout.addWidget(self.Rcir, 2, 1, 1, 1)
        self.rsjcir_lb = QtWidgets.QLabel(self.tab_1)
        self.rsjcir_lb.setObjectName("rsjcir_lb")
        self.gridLayout.addWidget(self.rsjcir_lb, 10, 0, 1, 1)
        self.Hreclb = QtWidgets.QLabel(self.tab_1)
        self.Hreclb.setObjectName("Hreclb")
        self.gridLayout.addWidget(self.Hreclb, 0, 0, 1, 1)
        self.rsjcir = QtWidgets.QLineEdit(self.tab_1)
        self.rsjcir.setObjectName("rsjcir")
        self.gridLayout.addWidget(self.rsjcir, 10, 1, 1, 1)
        self.Brec_lb = QtWidgets.QLabel(self.tab_1)
        self.Brec_lb.setObjectName("Brec_lb")
        self.gridLayout.addWidget(self.Brec_lb, 1, 0, 1, 1)
        self.hpolk_lbl = QtWidgets.QLabel(self.tab_1)
        self.hpolk_lbl.setObjectName("hpolk_lbl")
        self.gridLayout.addWidget(self.hpolk_lbl, 3, 0, 1, 1)
        self.bpolk_lb = QtWidgets.QLabel(self.tab_1)
        self.bpolk_lb.setObjectName("bpolk_lb")
        self.gridLayout.addWidget(self.bpolk_lb, 4, 0, 1, 1)
        self.brebr_lb = QtWidgets.QLabel(self.tab_1)
        self.brebr_lb.setObjectName("brebr_lb")
        self.gridLayout.addWidget(self.brebr_lb, 6, 0, 1, 1)
        self.dlt_nbrec_lb = QtWidgets.QLabel(self.tab_1)
        self.dlt_nbrec_lb.setObjectName("dlt_nbrec_lb")
        self.gridLayout.addWidget(self.dlt_nbrec_lb, 9, 0, 1, 1)
        self.hrebr_lb = QtWidgets.QLabel(self.tab_1)
        self.hrebr_lb.setObjectName("hrebr_lb")
        self.gridLayout.addWidget(self.hrebr_lb, 5, 0, 1, 1)
        self.nbrcir_lb = QtWidgets.QLabel(self.tab_1)
        self.nbrcir_lb.setObjectName("nbrcir_lb")
        self.gridLayout.addWidget(self.nbrcir_lb, 8, 0, 1, 1)
        self.dlt_nbrec = QtWidgets.QLineEdit(self.tab_1)
        self.dlt_nbrec.setObjectName("dlt_nbrec")
        self.gridLayout.addWidget(self.dlt_nbrec, 9, 1, 1, 1)
        self.nsjcir = QtWidgets.QLineEdit(self.tab_1)
        self.nsjcir.setObjectName("nsjcir")
        self.gridLayout.addWidget(self.nsjcir, 11, 1, 1, 1)
        self.Rcir_lb = QtWidgets.QLabel(self.tab_1)
        self.Rcir_lb.setToolTip("")
        self.Rcir_lb.setStatusTip("")
        self.Rcir_lb.setObjectName("Rcir_lb")
        self.gridLayout.addWidget(self.Rcir_lb, 2, 0, 1, 1)
        self.Hrec = QtWidgets.QLineEdit(self.tab_1)
        self.Hrec.setObjectName("Hrec")
        self.gridLayout.addWidget(self.Hrec, 0, 1, 1, 1)
        self.Brec = QtWidgets.QLineEdit(self.tab_1)
        self.Brec.setObjectName("Brec")
        self.gridLayout.addWidget(self.Brec, 1, 1, 1, 1)
        self.a1a2rec_lb = QtWidgets.QLabel(self.tab_1)
        self.a1a2rec_lb.setObjectName("a1a2rec_lb")
        self.gridLayout.addWidget(self.a1a2rec_lb, 12, 0, 1, 1)
        self.kslb = QtWidgets.QLineEdit(self.tab_1)
        self.kslb.setObjectName("kslb")
        self.gridLayout.addWidget(self.kslb, 19, 1, 1, 1)
        self.stepslb_lb = QtWidgets.QLabel(self.tab_1)
        self.stepslb_lb.setObjectName("stepslb_lb")
        self.gridLayout.addWidget(self.stepslb_lb, 23, 0, 1, 1)
        self.dsjslb_lb = QtWidgets.QLabel(self.tab_1)
        self.dsjslb_lb.setObjectName("dsjslb_lb")
        self.gridLayout.addWidget(self.dsjslb_lb, 21, 0, 1, 1)
        self.dsjslb = QtWidgets.QLineEdit(self.tab_1)
        self.dsjslb.setObjectName("dsjslb")
        self.gridLayout.addWidget(self.dsjslb, 21, 1, 1, 1)
        self.ns1ns2rec_lb = QtWidgets.QLabel(self.tab_1)
        self.ns1ns2rec_lb.setObjectName("ns1ns2rec_lb")
        self.gridLayout.addWidget(self.ns1ns2rec_lb, 13, 0, 1, 1)
        self.asslb_lb = QtWidgets.QLabel(self.tab_1)
        self.asslb_lb.setObjectName("asslb_lb")
        self.gridLayout.addWidget(self.asslb_lb, 20, 0, 1, 1)
        self.a1a2rec = QtWidgets.QLineEdit(self.tab_1)
        self.a1a2rec.setObjectName("a1a2rec")
        self.gridLayout.addWidget(self.a1a2rec, 12, 1, 1, 1)
        self.hslb = QtWidgets.QLineEdit(self.tab_1)
        self.hslb.setObjectName("hslb")
        self.gridLayout.addWidget(self.hslb, 18, 1, 1, 1)
        self.alpha_lb = QtWidgets.QLabel(self.tab_1)
        self.alpha_lb.setObjectName("alpha_lb")
        self.gridLayout.addWidget(self.alpha_lb, 22, 0, 1, 1)
        self.ns1ns2rec = QtWidgets.QLineEdit(self.tab_1)
        self.ns1ns2rec.setObjectName("ns1ns2rec")
        self.gridLayout.addWidget(self.ns1ns2rec, 13, 1, 1, 1)
        self.dsjcir_lb = QtWidgets.QLabel(self.tab_1)
        self.dsjcir_lb.setObjectName("dsjcir_lb")
        self.gridLayout.addWidget(self.dsjcir_lb, 15, 0, 1, 1)
        self.ds1ds2rec = QtWidgets.QLineEdit(self.tab_1)
        self.ds1ds2rec.setObjectName("ds1ds2rec")
        self.gridLayout.addWidget(self.ds1ds2rec, 16, 1, 1, 1)
        self.kslb_lb = QtWidgets.QLabel(self.tab_1)
        self.kslb_lb.setObjectName("kslb_lb")
        self.gridLayout.addWidget(self.kslb_lb, 19, 0, 1, 1)
        self.ds1ds2rec_lb = QtWidgets.QLabel(self.tab_1)
        self.ds1ds2rec_lb.setObjectName("ds1ds2rec_lb")
        self.gridLayout.addWidget(self.ds1ds2rec_lb, 16, 0, 1, 1)
        self.alpha = QtWidgets.QLineEdit(self.tab_1)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 22, 1, 1, 1)
        self.hslb_lb = QtWidgets.QLabel(self.tab_1)
        self.hslb_lb.setObjectName("hslb_lb")
        self.gridLayout.addWidget(self.hslb_lb, 18, 0, 1, 1)
        self.asslb = QtWidgets.QLineEdit(self.tab_1)
        self.asslb.setObjectName("asslb")
        self.gridLayout.addWidget(self.asslb, 20, 1, 1, 1)
        self.dsjcir = QtWidgets.QLineEdit(self.tab_1)
        self.dsjcir.setObjectName("dsjcir")
        self.gridLayout.addWidget(self.dsjcir, 15, 1, 1, 1)
        self.stepslb = QtWidgets.QLineEdit(self.tab_1)
        self.stepslb.setObjectName("stepslb")
        self.gridLayout.addWidget(self.stepslb, 23, 1, 1, 1)
        self.ns1ns2tvr_lb = QtWidgets.QLabel(self.tab_1)
        self.ns1ns2tvr_lb.setObjectName("ns1ns2tvr_lb")
        self.gridLayout.addWidget(self.ns1ns2tvr_lb, 14, 0, 1, 1)
        self.ns1ns2tvr = QtWidgets.QLineEdit(self.tab_1)
        self.ns1ns2tvr.setObjectName("ns1ns2tvr")
        self.gridLayout.addWidget(self.ns1ns2tvr, 14, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.horizontalLayout_7.addWidget(self.groupBox, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        self.comboBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout_2.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_7.sizePolicy().hasHeightForWidth())
        self.radioButton_7.setSizePolicy(sizePolicy)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_5.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_8.sizePolicy().hasHeightForWidth())
        self.radioButton_8.setSizePolicy(sizePolicy)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_5.addWidget(self.radioButton_8)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_9.sizePolicy().hasHeightForWidth())
        self.radioButton_9.setSizePolicy(sizePolicy)
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_9.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_10.sizePolicy().hasHeightForWidth())
        self.radioButton_10.setSizePolicy(sizePolicy)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_9.addWidget(self.radioButton_10)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recpic = QtWidgets.QLabel(self.centralwidget)
        self.recpic.setFocusPolicy(QtCore.Qt.NoFocus)
        self.recpic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recpic.setText("")
        self.recpic.setPixmap(QtGui.QPixmap("../Rec.png"))
        self.recpic.setObjectName("recpic")
        self.horizontalLayout_3.addWidget(self.recpic)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_6.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.clicked['bool'].connect(MainWindow.deleteLater)
        self.circ.clicked['bool'].connect(self.Brec.hide)
        self.circ.clicked['bool'].connect(self.Brec_lb.hide)
        self.rect.clicked['bool'].connect(self.Brec_lb.show)
        self.rect.clicked['bool'].connect(self.Brec.show)
        self.circ.clicked['bool'].connect(self.Hrec.hide)
        self.rect.clicked['bool'].connect(self.recpic.show)
        self.tavr.clicked['bool'].connect(self.recpic.show)
        self.rect.clicked['bool'].connect(self.Rcir.hide)
        self.rect.clicked['bool'].connect(self.nsjcir.hide)
        self.rect.clicked['bool'].connect(self.nbRcir_lb.hide)
        self.rect.clicked['bool'].connect(self.nsjcir_lb.hide)
        self.rect.clicked['bool'].connect(self.rsjcir.hide)
        self.rect.clicked['bool'].connect(self.rsjcir_lb.hide)
        self.circ.clicked['bool'].connect(self.recpic.show)
        self.circ.clicked['bool'].connect(self.Hreclb.hide)
        self.circ.clicked['bool'].connect(self.dlt_nbrec.hide)
        self.circ.clicked['bool'].connect(self.dlt_nbrec_lb.hide)
        self.rect.clicked['bool'].connect(self.ns1ns2rec.show)
        self.rect.clicked['bool'].connect(self.ns1ns2rec_lb.show)
        self.rect.clicked['bool'].connect(self.dsjcir.hide)
        self.rect.clicked['bool'].connect(self.Rcir.hide)
        self.rect.clicked['bool'].connect(self.Rcir_lb.hide)
        self.rect.clicked['bool'].connect(self.Hrec.show)
        self.rect.clicked['bool'].connect(self.Hreclb.show)
        self.rect.clicked['bool'].connect(self.nbRcir.hide)
        self.rect.clicked['bool'].connect(self.nbrcir_lb.hide)
        self.rect.clicked['bool'].connect(self.nbrcir.hide)
        self.rect.clicked['bool'].connect(self.dsjcir_lb.hide)
        self.circ.clicked['bool'].connect(self.a1a2rec.hide)
        self.circ.clicked['bool'].connect(self.a1a2rec_lb.hide)
        self.circ.clicked['bool'].connect(self.ds1ds2rec_lb.hide)
        self.circ.clicked['bool'].connect(self.ds1ds2rec.hide)
        self.circ.clicked['bool'].connect(self.Rcir.show)
        self.circ.clicked['bool'].connect(self.Rcir_lb.show)
        self.circ.clicked['bool'].connect(self.nbRcir.show)
        self.circ.clicked['bool'].connect(self.nbRcir_lb.show)
        self.circ.clicked['bool'].connect(self.nsjcir.show)
        self.circ.clicked['bool'].connect(self.nsjcir_lb.show)
        self.circ.clicked['bool'].connect(self.rsjcir.show)
        self.circ.clicked['bool'].connect(self.rsjcir_lb.show)
        self.circ.clicked['bool'].connect(self.dsjcir.show)
        self.circ.clicked['bool'].connect(self.dsjcir_lb.show)
        self.rect.clicked['bool'].connect(self.dlt_nbrec_lb.show)
        self.rect.clicked['bool'].connect(self.dlt_nbrec.show)
        self.circ.clicked['bool'].connect(self.ns1ns2rec.hide)
        self.circ.clicked['bool'].connect(self.ns1ns2rec_lb.hide)
        self.rect.clicked['bool'].connect(self.a1a2rec.show)
        self.rect.clicked['bool'].connect(self.a1a2rec_lb.show)
        self.rect.clicked['bool'].connect(self.ds1ds2rec.show)
        self.rect.clicked['bool'].connect(self.ds1ds2rec_lb.show)
        self.rect.clicked['bool'].connect(self.hpolk.hide)
        self.circ.clicked['bool'].connect(self.hpolk.hide)
        self.circ.clicked['bool'].connect(self.bpolk_lb.hide)
        self.circ.clicked['bool'].connect(self.bpolk.hide)
        self.rect.clicked['bool'].connect(self.hrebr.hide)
        self.circ.clicked['bool'].connect(self.hrebr.hide)
        self.circ.clicked['bool'].connect(self.brebr.hide)
        self.rect.clicked['bool'].connect(self.brebr.hide)
        self.circ.clicked['bool'].connect(self.hpolk_lbl.hide)
        self.tavr.clicked['bool'].connect(self.brebr.show)
        self.tavr.clicked['bool'].connect(self.hrebr_lb.show)
        self.tavr.clicked['bool'].connect(self.brebr_lb.show)
        self.tavr.clicked['bool'].connect(self.bpolk_lb.show)
        self.circ.clicked['bool'].connect(self.hrebr_lb.hide)
        self.tavr.clicked['bool'].connect(self.bpolk.show)
        self.circ.clicked['bool'].connect(self.brebr_lb.hide)
        self.rect.clicked['bool'].connect(self.hrebr_lb.hide)
        self.rect.clicked['bool'].connect(self.brebr_lb.hide)
        self.tavr.clicked['bool'].connect(self.nbRcir.hide)
        self.tavr.clicked['bool'].connect(self.dsjcir_lb.hide)
        self.tavr.clicked['bool'].connect(self.Rcir_lb.hide)
        self.tavr.clicked['bool'].connect(self.dsjcir.hide)
        self.tavr.clicked['bool'].connect(self.Rcir.hide)
        self.tavr.clicked['bool'].connect(self.Brec.hide)
        self.tavr.clicked['bool'].connect(self.Hreclb.hide)
        self.tavr.clicked['bool'].connect(self.Hrec.hide)
        self.tavr.clicked['bool'].connect(self.Brec_lb.hide)
        self.tavr.clicked['bool'].connect(self.nbrcir_lb.hide)
        self.tavr.clicked['bool'].connect(self.rsjcir.hide)
        self.tavr.clicked['bool'].connect(self.rsjcir_lb.hide)
        self.tavr.clicked['bool'].connect(self.nsjcir_lb.hide)
        self.rect.clicked['bool'].connect(self.hpolk_lbl.hide)
        self.rect.clicked['bool'].connect(self.bpolk.hide)
        self.rect.clicked['bool'].connect(self.bpolk_lb.hide)
        self.circ.clicked['bool'].connect(self.nbrcir.show)
        self.circ.clicked['bool'].connect(self.nbrcir_lb.show)
        self.tavr.clicked['bool'].connect(self.nbRcir_lb.hide)
        self.tavr.clicked['bool'].connect(self.nbrcir.hide)
        self.tavr.clicked['bool'].connect(self.nsjcir.hide)
        self.tavr.clicked['bool'].connect(self.hrebr.show)
        self.tavr.clicked['bool'].connect(self.dlt_nbrec.show)
        self.tavr.clicked['bool'].connect(self.dlt_nbrec_lb.show)
        self.tavr.clicked['bool'].connect(self.ns1ns2rec.show)
        self.tavr.clicked['bool'].connect(self.ns1ns2rec_lb.show)
        self.tavr.clicked['bool'].connect(self.ds1ds2rec.show)
        self.tavr.clicked['bool'].connect(self.ds1ds2rec_lb.show)
        self.tavr.clicked['bool'].connect(self.a1a2rec.show)
        self.tavr.clicked['bool'].connect(self.a1a2rec_lb.show)
        self.tavr.clicked['bool'].connect(self.hpolk.show)
        self.tavr.clicked['bool'].connect(self.hpolk_lbl.show)
        self.tavr.clicked['bool'].connect(self.ns1ns2tvr.show)
        self.tavr.clicked['bool'].connect(self.ns1ns2tvr_lb.show)
        self.rect.clicked['bool'].connect(self.ns1ns2tvr.hide)
        self.rect.clicked['bool'].connect(self.ns1ns2tvr_lb.hide)
        self.circ.clicked['bool'].connect(self.ns1ns2tvr.hide)
        self.circ.clicked['bool'].connect(self.ns1ns2tvr_lb.hide)
        self.shell.clicked['bool'].connect(self.Brec.hide)
        self.shell.clicked['bool'].connect(self.Brec_lb.hide)
        self.shell.clicked['bool'].connect(self.Hrec.hide)
        self.shell.clicked['bool'].connect(self.Rcir.hide)
        self.shell.clicked['bool'].connect(self.Rcir_lb.hide)
        self.shell.clicked['bool'].connect(self.a1a2rec.hide)
        self.shell.clicked['bool'].connect(self.a1a2rec_lb.hide)
        self.shell.clicked['bool'].connect(self.bpolk.hide)
        self.shell.clicked['bool'].connect(self.bpolk_lb.hide)
        self.shell.clicked['bool'].connect(self.brebr.hide)
        self.shell.clicked['bool'].connect(self.brebr_lb.hide)
        self.shell.clicked['bool'].connect(self.dlt_nbrec.hide)
        self.shell.clicked['bool'].connect(self.dlt_nbrec_lb.hide)
        self.tavr.clicked['bool'].connect(self.ns1ns2rec.hide)
        self.tavr.clicked['bool'].connect(self.ns1ns2rec_lb.hide)
        self.shell.clicked['bool'].connect(self.Hreclb.hide)
        self.shell.clicked['bool'].connect(self.hpolk.hide)
        self.shell.clicked['bool'].connect(self.hpolk_lbl.hide)
        self.shell.clicked['bool'].connect(self.hrebr.hide)
        self.shell.clicked['bool'].connect(self.hrebr_lb.hide)
        self.shell.clicked['bool'].connect(self.ns1ns2tvr.hide)
        self.shell.clicked['bool'].connect(self.ns1ns2tvr_lb.hide)
        self.circ.clicked['bool'].connect(self.hslb.hide)
        self.circ.clicked['bool'].connect(self.hslb_lb.hide)
        self.circ.clicked['bool'].connect(self.kslb.hide)
        self.circ.clicked['bool'].connect(self.kslb_lb.hide)
        self.circ.clicked['bool'].connect(self.asslb.hide)
        self.circ.clicked['bool'].connect(self.asslb_lb.hide)
        self.circ.clicked['bool'].connect(self.dsjslb.hide)
        self.circ.clicked['bool'].connect(self.dsjslb_lb.hide)
        self.circ.clicked['bool'].connect(self.alpha.hide)
        self.circ.clicked['bool'].connect(self.alpha_lb.hide)
        self.circ.clicked['bool'].connect(self.stepslb.hide)
        self.circ.clicked['bool'].connect(self.stepslb_lb.hide)
        self.rect.clicked['bool'].connect(self.hslb.hide)
        self.rect.clicked['bool'].connect(self.hslb_lb.hide)
        self.rect.clicked['bool'].connect(self.kslb.hide)
        self.rect.clicked['bool'].connect(self.asslb.hide)
        self.rect.clicked['bool'].connect(self.asslb_lb.hide)
        self.rect.clicked['bool'].connect(self.alpha.hide)
        self.rect.clicked['bool'].connect(self.alpha_lb.hide)
        self.rect.clicked['bool'].connect(self.stepslb.hide)
        self.rect.clicked['bool'].connect(self.stepslb_lb.hide)
        self.tavr.clicked['bool'].connect(self.hslb.hide)
        self.tavr.clicked['bool'].connect(self.hslb_lb.hide)
        self.tavr.clicked['bool'].connect(self.kslb.hide)
        self.tavr.clicked['bool'].connect(self.kslb_lb.hide)
        self.tavr.clicked['bool'].connect(self.asslb.hide)
        self.tavr.clicked['bool'].connect(self.asslb_lb.hide)
        self.tavr.clicked['bool'].connect(self.dsjslb.hide)
        self.tavr.clicked['bool'].connect(self.dsjslb_lb.hide)
        self.tavr.clicked['bool'].connect(self.alpha.hide)
        self.tavr.clicked['bool'].connect(self.alpha_lb.hide)
        self.tavr.clicked['bool'].connect(self.stepslb.hide)
        self.tavr.clicked['bool'].connect(self.stepslb_lb.hide)
        self.shell.clicked['bool'].connect(self.hslb.show)
        self.shell.clicked['bool'].connect(self.hslb_lb.show)
        self.shell.clicked['bool'].connect(self.kslb.show)
        self.shell.clicked['bool'].connect(self.kslb_lb.show)
        self.shell.clicked['bool'].connect(self.asslb.show)
        self.shell.clicked['bool'].connect(self.asslb_lb.show)
        self.shell.clicked['bool'].connect(self.dsjslb.show)
        self.shell.clicked['bool'].connect(self.dsjslb_lb.show)
        self.shell.clicked['bool'].connect(self.alpha.show)
        self.shell.clicked['bool'].connect(self.alpha_lb.show)
        self.shell.clicked['bool'].connect(self.stepslb.show)
        self.shell.clicked['bool'].connect(self.stepslb_lb.show)
        self.rect.clicked['bool'].connect(self.kslb_lb.hide)
        self.rect.clicked['bool'].connect(self.dsjslb.hide)
        self.rect.clicked['bool'].connect(self.dsjslb_lb.hide)
        self.shell.clicked['bool'].connect(self.ds1ds2rec.hide)
        self.shell.clicked['bool'].connect(self.ds1ds2rec_lb.hide)
        self.shell.clicked['bool'].connect(self.ns1ns2rec.hide)
        self.shell.clicked['bool'].connect(self.ns1ns2rec_lb.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RC"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Element"))
        self.rect.setText(_translate("MainWindow", "Rectangle"))
        self.circ.setText(_translate("MainWindow", "Circle"))
        self.tavr.setText(_translate("MainWindow", "Tavr"))
        self.shell.setText(_translate("MainWindow", "Slab"))
        self.bpolk.setToolTip(_translate("MainWindow", "Width of plate"))
        self.bpolk.setStatusTip(_translate("MainWindow", "Width of plate"))
        self.bpolk.setText(_translate("MainWindow", "1.1"))
        self.hpolk.setToolTip(_translate("MainWindow", "Length of plate"))
        self.hpolk.setStatusTip(_translate("MainWindow", "Length of plate"))
        self.hpolk.setText(_translate("MainWindow", "0.3"))
        self.brebr.setToolTip(_translate("MainWindow", "Width of wall"))
        self.brebr.setStatusTip(_translate("MainWindow", "Width of wall"))
        self.brebr.setText(_translate("MainWindow", "0.3"))
        self.hrebr.setToolTip(_translate("MainWindow", "Hight of wall"))
        self.hrebr.setStatusTip(_translate("MainWindow", "Hight of wall"))
        self.hrebr.setText(_translate("MainWindow", "0.5"))
        self.nbRcir_lb.setText(_translate("MainWindow", "nb_R,шт"))
        self.nbRcir.setToolTip(_translate("MainWindow", "Count of segment"))
        self.nbRcir.setStatusTip(_translate("MainWindow", "Count of segment"))
        self.nbRcir.setText(_translate("MainWindow", "24"))
        self.nbrcir.setToolTip(_translate("MainWindow", "Number divisions of radius"))
        self.nbrcir.setStatusTip(_translate("MainWindow", "Number divisions of radius"))
        self.nbrcir.setText(_translate("MainWindow", "10"))
        self.nsjcir_lb.setText(_translate("MainWindow", "nsj,шт"))
        self.Rcir.setToolTip(_translate("MainWindow", "Radius of section"))
        self.Rcir.setStatusTip(_translate("MainWindow", "Radius of section"))
        self.Rcir.setText(_translate("MainWindow", "0.3"))
        self.rsjcir_lb.setText(_translate("MainWindow", "rsj,м"))
        self.Hreclb.setText(_translate("MainWindow", "Н,м"))
        self.rsjcir.setToolTip(_translate("MainWindow", "Radius for rebar"))
        self.rsjcir.setStatusTip(_translate("MainWindow", "Radius for rebar"))
        self.rsjcir.setText(_translate("MainWindow", "0.252,0.2,0.1"))
        self.Brec_lb.setText(_translate("MainWindow", "B,м"))
        self.hpolk_lbl.setText(_translate("MainWindow", "Hpolk,м"))
        self.bpolk_lb.setText(_translate("MainWindow", "Bpolk,м"))
        self.brebr_lb.setText(_translate("MainWindow", "Brebr,м"))
        self.dlt_nbrec_lb.setText(_translate("MainWindow", "Δnb,м"))
        self.hrebr_lb.setText(_translate("MainWindow", "Hrebr,м"))
        self.nbrcir_lb.setText(_translate("MainWindow", "nb_r,шт"))
        self.dlt_nbrec.setToolTip(_translate("MainWindow", "minimal dimension mesh"))
        self.dlt_nbrec.setStatusTip(_translate("MainWindow", "minimal dimension mesh"))
        self.dlt_nbrec.setText(_translate("MainWindow", "0.02"))
        self.nsjcir.setToolTip(_translate("MainWindow", "number of rebars on the radius"))
        self.nsjcir.setStatusTip(_translate("MainWindow", "number of rebars on the radius"))
        self.nsjcir.setText(_translate("MainWindow", "8,5,8"))
        self.Rcir_lb.setText(_translate("MainWindow", "R,м"))
        self.Hrec.setToolTip(_translate("MainWindow", "Hight of section"))
        self.Hrec.setStatusTip(_translate("MainWindow", "Hight of section"))
        self.Hrec.setText(_translate("MainWindow", "0.6"))
        self.Brec.setToolTip(_translate("MainWindow", "Width of section"))
        self.Brec.setStatusTip(_translate("MainWindow", "Width of section"))
        self.Brec.setText(_translate("MainWindow", "0.4"))
        self.a1a2rec_lb.setText(_translate("MainWindow", "a1,a2,м"))
        self.kslb.setToolTip(_translate("MainWindow", "Number layers of hight"))
        self.kslb.setStatusTip(_translate("MainWindow", "Number layers of hight"))
        self.kslb.setText(_translate("MainWindow", "21"))
        self.stepslb_lb.setText(_translate("MainWindow", "step,м"))
        self.dsjslb_lb.setText(_translate("MainWindow", "dsj,м"))
        self.dsjslb.setToolTip(_translate("MainWindow", "diameter of rebars "))
        self.dsjslb.setStatusTip(_translate("MainWindow", "diameter of rebars"))
        self.dsjslb.setText(_translate("MainWindow", "0.025,0.025,0.025,0.025"))
        self.ns1ns2rec_lb.setText(_translate("MainWindow", "ns1,ns2,шт"))
        self.asslb_lb.setText(_translate("MainWindow", "a1,a2,м"))
        self.a1a2rec.setToolTip(_translate("MainWindow", "as1 - cover of rebars on H, as2 - cover of rebars on B"))
        self.a1a2rec.setStatusTip(_translate("MainWindow", "as1 - cover of rebars on H, as2 - cover of rebars on B"))
        self.a1a2rec.setText(_translate("MainWindow", "0.05,0.05"))
        self.hslb.setToolTip(_translate("MainWindow", "Hight of slab"))
        self.hslb.setStatusTip(_translate("MainWindow", "Hight of slab"))
        self.hslb.setText(_translate("MainWindow", "0.5"))
        self.alpha_lb.setText(_translate("MainWindow", "alpha,(°)"))
        self.ns1ns2rec.setStatusTip(_translate("MainWindow", "ns1 - count of rebars on H, ns2 - count of rebars on B"))
        self.ns1ns2rec.setText(_translate("MainWindow", "2,3"))
        self.dsjcir_lb.setText(_translate("MainWindow", "dsj,м"))
        self.ds1ds2rec.setToolTip(_translate("MainWindow", "ds1 - diameter of rebars on H, ds2 - diameter of rebars on B"))
        self.ds1ds2rec.setStatusTip(_translate("MainWindow", "ds1 - diameter of rebars on H, ds2 - diameter of rebars on B"))
        self.ds1ds2rec.setText(_translate("MainWindow", "0.01,0.025"))
        self.kslb_lb.setText(_translate("MainWindow", "K,шт"))
        self.ds1ds2rec_lb.setText(_translate("MainWindow", "ds1,ds2,м"))
        self.alpha.setToolTip(_translate("MainWindow", "rotation angle of rebars"))
        self.alpha.setStatusTip(_translate("MainWindow", "rotation angle of rebars"))
        self.alpha.setText(_translate("MainWindow", "0,90,90,0"))
        self.hslb_lb.setText(_translate("MainWindow", "H,м"))
        self.asslb.setToolTip(_translate("MainWindow", "as1 - cover of top, as2 - cover of bottom"))
        self.asslb.setStatusTip(_translate("MainWindow", "as1 - cover of top, as2 - cover of bottom"))
        self.asslb.setText(_translate("MainWindow", "0.05,0.05"))
        self.dsjcir.setToolTip(_translate("MainWindow", "diameter of rebars оn rsj radius"))
        self.dsjcir.setStatusTip(_translate("MainWindow", "diameter of rebars оn rsj radius"))
        self.dsjcir.setText(_translate("MainWindow", "0.025,0.025,0.01"))
        self.stepslb.setToolTip(_translate("MainWindow", "step of rebars"))
        self.stepslb.setStatusTip(_translate("MainWindow", "step of rebars"))
        self.stepslb.setText(_translate("MainWindow", "0.2,0.2,0.2,0.2"))
        self.ns1ns2tvr_lb.setText(_translate("MainWindow", "ns1,ns2,м"))
        self.ns1ns2tvr.setToolTip(_translate("MainWindow", "ns1 - count of rebars on H, ns2 - count of rebars on B"))
        self.ns1ns2tvr.setStatusTip(_translate("MainWindow", "ns1 - count of rebars on H, ns2 - count of rebars on B"))
        self.ns1ns2tvr.setText(_translate("MainWindow", "5,4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Geometry"))
        self.groupBox.setTitle(_translate("MainWindow", "Density"))
        self.radioButton_3.setText(_translate("MainWindow", "Heavy"))
        self.radioButton_4.setText(_translate("MainWindow", "Light"))
        self.lineEdit_8.setToolTip(_translate("MainWindow", "Poisson\'s ratio"))
        self.lineEdit_8.setStatusTip(_translate("MainWindow", "Poisson\'s ratio"))
        self.comboBox_2.setToolTip(_translate("MainWindow", "Relative humidity"))
        self.comboBox_2.setStatusTip(_translate("MainWindow", "Relative humidity"))
        self.comboBox_1.setToolTip(_translate("MainWindow", "Grade of concrete"))
        self.label.setText(_translate("MainWindow", "Grade of concrete"))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "gb factor <=1"))
        self.lineEdit_5.setStatusTip(_translate("MainWindow", "gb factor <=1"))
        self.label_2.setText(_translate("MainWindow", "Relative humidity"))
        self.label_3.setText(_translate("MainWindow", "Poisson\'s ratio"))
        self.label_4.setText(_translate("MainWindow", "Ɣb3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Concrete"))
        self.comboBox_4.setToolTip(_translate("MainWindow", "Grade of tendons steel"))
        self.comboBox_4.setStatusTip(_translate("MainWindow", "Grade of tendons steel"))
        self.comboBox_3.setToolTip(_translate("MainWindow", "Grade of rebars steel"))
        self.comboBox_3.setStatusTip(_translate("MainWindow", "Grade of rebars steel"))
        self.label_5.setText(_translate("MainWindow", "Grade of rebars steel"))
        self.label_6.setText(_translate("MainWindow", "Grade of tendons steel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Reinforcement"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Loads duration"))
        self.radioButton_7.setText(_translate("MainWindow", "Short"))
        self.radioButton_8.setText(_translate("MainWindow", "Long"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Limit state"))
        self.radioButton_9.setText(_translate("MainWindow", "1_st"))
        self.radioButton_10.setText(_translate("MainWindow", "2_st"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Loads"))
        self.pushButton_1.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))
